### ISSUE TITLE
low recall on sift1M dataset using hnsw

### ISSUE THREAD

**Issue by DragonDriver** [vearch/vearch#220]
Hello, it's me again.

I deploy single-node vearch using https://github.com/vearch/vearch/blob/master/docs/BinaryInstallation.md

Using hnsw, I got very low recall on sift1M dataset which is lower than 45%

However, under all same configuration, recall can be up to 99% using ivfpq

So, how can I improve the recall using hnsw?

**Comment by DragonDriver** [comment]
create table:

```python
{
            "name": "test",
            "partition_num": 1,
            "replica_num": 1,
            "engine": {
                "name": "gamma",
                "max_size": 1000000,
                "retrieval_type": "HNSW",
                "retrieval_param": retrieval_param
            },
            "properties": {
                "field1": {
                    "type": "vector",
                    "index": True,
                    "dimension": dimension
                }
            }
}
```

nlinks, efConstruction, efSearch:

```yaml
        efConstruction-80:
          args: [[16], [80], [10, 20, 30, 40, 50, 60, 70]]
        efConstruction-200:
          args: [[16], [200], [10, 20, 30, 40, 50, 70, 100, 150, 200]]
        nlinks-8:
          args: [[8], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
        nlinks-12:
          args: [[12], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
        nlinks-16:
          args: [[16], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
        nlinks-24:
          args: [[24], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
        nlinks-36:
          args: [[36], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
        nlinks-48:
          args: [[48], [500], [10, 20, 40, 80, 120, 200, 400, 600, 800]]
```

bulk search:

```python
{
            "query": {
                "sum": [{
                    "field": "field1",
                    "feature": features,
                }]
            },
            "size": 10,
            "sort": [{
                "_score": {"order": "asc"}
            }]
}
```
